### PR TITLE
#WOB-701 fix specialchars timer

### PR DESCRIPTION
**Pull request by SergeyPish**

### CODE REVIEW

**Comment by athlonUA** [comment]
@SergeyPish I've created reverted commit https://github.com/wbbly/time-api/commit/d08fe9e251acf719aaf2523f8a7c0921a02b6a58  because of issue with `"` and `%`

**Comment by athlonUA** [comment]
Please check all your changes again

**Comment by pilot** [comment]
@SergeyPish rebase pls, check comments and fix

**Comment by pilot** [comment]
@athlonUA does it ok?

**Comment by athlonUA** [comment]
On testing stage now...

**Pull request closed without merging**
